version: '3.8'

services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal"
    volumes:
      - dynamodb_data:/home/dynamodblocal

  dynamodb-init:
    image: node:18-alpine
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: >
      sh -c "
        apk add --no-cache curl &&
        until curl -s http://dynamodb:8000 > /dev/null; do
          echo 'Waiting for DynamoDB...' &&
          sleep 1;
        done &&
        npm install &&
        node scripts/local/init-dynamodb.js
      "
    depends_on:
      - dynamodb

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb:8000
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
    depends_on:
      - dynamodb

volumes:
  dynamodb_data: 