version: '3.8'

services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal"
    volumes:
      - dynamodb_data:/home/dynamodblocal

  dynamodb-init:
    image: node:18-alpine
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: >
      sh -c "
        apk add --no-cache curl &&
        until curl -s http://dynamodb:8000 > /dev/null; do
          echo 'Waiting for DynamoDB...' &&
          sleep 1;
        done &&
        npm install &&
        node scripts/local/init-dynamodb.js
      "
    depends_on:
      - dynamodb

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb:8000
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
    depends_on:
      - dynamodb

  localstack:
    image: localstack/localstack:3.3
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=sqs
      - DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - localstack_data:/var/lib/localstack

  sqs-init:
    image: node:18-alpine
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: >
      sh -c "
        apk add --no-cache curl &&
        until curl -s http://localstack:4566/_localstack/health > /dev/null; do
          echo 'Waiting for LocalStack SQS...' &&
          sleep 1;
        done &&
        npm install &&
        node scripts/local/init-sqs.js
      "
    depends_on:
      - localstack

volumes:
  dynamodb_data:
  localstack_data: 